### ISSUE TITLE
storage datalake support

### ISSUE THREAD

**Issue by tcz001** [tombuildsstuff/giovanni#10]
thanks for creating this repo, this actually solve the problem of versioning apis called from terraform, but now the datalake storage is not supported, can we make it also here?

**Comment by tombuildsstuff** [comment]
@tcz001 I agree this'd be a good addition for this project to support, but unfortunately we don't have a timeline to add support for this.

If you're interested in seeing support for this in the interim we'd be more than happy to review a PR / provide guidance if you're interested :)

Thanks!

**Comment by tcz001** [comment]
thanks for reply, sure i will be working on this to see if it can be achieved quickly

**Comment by LucaPrete** [comment]
I see in the comments 0.5.0. Does it mean we'll need to wait 0.5.0 to come out to have this feature? Any chance it could be included in 0.34?

**Comment by tombuildsstuff** [comment]
@LucaPrete there's two different projects - this one (Giovanni, the SDK we use to talk with the Azure API's) has shipped support for this in 0.6.0. The next step for this would be to add a new resource in the [Terraform Provider for Azure](https://github.com/terraform-providers/terraform-provider-azurerm) where when that's added that'll ship in the next available version of the Azure Provider.
