### ISSUE TITLE
Static Website Support

### ISSUE THREAD

**Issue by tombuildsstuff** [tombuildsstuff/giovanni#17]
The Azure Storage API's expose the ability to configure Static Websites via the `SetServiceProperties` call on the Blob Account: https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-service-properties (and retrieve it using GetServiceProperties)

Whilst these methods are exposed in the Azure SDK for Go - they're not complete:

https://github.com/Azure/azure-sdk-for-go/blob/v33.3.0/services/storage/mgmt/2019-04-01/storage/models.go#L1268-L1277

as such it'd be worthwhile to add these to Giovanni so that we can configure Static Websites for Blob Storage Accounts which unblocks https://github.com/terraform-providers/terraform-provider-azurerm/issues/1903

From an implementation perspective this is presumably should be within a new `accounts` package within the Blob package: https://github.com/tombuildsstuff/giovanni/tree/master/storage/2018-11-09/blob and just for these two methods

**Comment by timja** [comment]
I've made a start to it here:
https://github.com/tombuildsstuff/giovanni/pull/21

It works but needs some polish

Any feedback from you on design, structuring, testing etc would be greatly valued @tombuildsstuff
