### ISSUE TITLE
Shared Access Signature

### ISSUE THREAD

**Issue by kpfaulkner** [tombuildsstuff/giovanni#48]
Hi

Not a bug report but a question. Does this project handle shared access signatures as a method of auth? I don't immediately see the option but wanted to check before I dig any deeper.

Thanks

Ken

**Comment by tombuildsstuff** [comment]
Hey @kpfaulkner 

It does - `Azure/go-autorest` exposes a `SASTokenAuthorizer`, which you can use like so: https://github.com/hashicorp/terraform/blob/6bed3008a5d993bd89b2dafa101ebcd9cbced5a0/backend/remote-state/azure/arm_client.go#L135-L146. Whilst I've not tested it with anything other than Blobs, in theory it should be fine for the other items too.

Hope that helps!

**Comment by kpfaulkner** [comment]
Cheers @tombuildsstuff , exactly what I'm after.

Thanks again!
