### ISSUE TITLE
No NewSharedKeyLiteTableAuthorizer api in autorest package in example

### ISSUE THREAD

**Issue by Murphy-OrangeMud** [tombuildsstuff/giovanni#52]
![image](https://user-images.githubusercontent.com/46390322/129667877-fde1987f-9068-4fab-91d2-b4085a478275.png)
![image](https://user-images.githubusercontent.com/46390322/129667959-2a4129a3-4c4c-4ae2-9fcc-2057860dce12.png)

**Comment by tombuildsstuff** [comment]
hi @Murphy-OrangeMud 

This ended up being combined into [this Authorizer](https://github.com/Azure/go-autorest/blob/76c7860e9b602854c8598676b7550c715c48a607/autorest/authorization_storage.go#L77-L88) which takes [one of these Constants](https://github.com/Azure/go-autorest/blob/76c7860e9b602854c8598676b7550c715c48a607/autorest/authorization_storage.go#L30-L48) - as such updating to use that Authorizer instead should fix this.

Thanks!
