### ISSUE TITLE
Extend the data plane URL with dns zone segment

### ISSUE THREAD

**Issue by magodo** [tombuildsstuff/giovanni#62]
There is a new public preview feature for storage account: https://techcommunity.microsoft.com/t5/azure-storage-blog/public-preview-create-additional-5000-azure-storage-accounts/ba-p/3465466. It introduced a new property `dnsEndpointType`, when it is set to `AzureDnsZone`, the endpoints of the sub-service are changed from the form: `myAccountname.[service type].[url]` to `myAccountname.[dnszone].[service type].[url]`.

This needs a change in this SDK, mostly around: [internal/endpoints/endpoints.go.](https://github.com/tombuildsstuff/giovanni/blob/19cebee2d658f7ef0475eeb4abd208a11225774f/storage/internal/endpoints/endpoints.go#L16)

Related to https://github.com/hashicorp/terraform-provider-azurerm/issues/17513

**Comment by tombuildsstuff** [comment]
This is supported in the new base layer, closing this in favour of https://github.com/tombuildsstuff/giovanni/issues/68 where this'll become available.
