### ISSUE TITLE
Support for fetching Blob Contents

### ISSUE THREAD

**Issue by gaui** [tombuildsstuff/giovanni#65]
Currently the SDK supports [fetching blob properties](https://learn.microsoft.com/en-us/rest/api/storageservices/get-blob), but I would like to suggest that it would also support fetching the blob _contents_. This would allow the Terraform AzureRM provider to add the `.contents` to its [attributes for the `azurerm_storage_blob` data source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/storage_blob#attributes-reference).

Reference issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/18779

**Comment by tombuildsstuff** [comment]
@gaui this is available here fwiw: https://github.com/tombuildsstuff/giovanni/blob/master/storage/2020-08-04/blob/blobs/get.go

**Comment by gaui** [comment]
API already implemented, closing.
