### ISSUE TITLE
Creating storage blob container returns XML errors which cannot be parsed

### ISSUE THREAD

**Issue by invidian** [tombuildsstuff/giovanni#7]
As a follow up to terraform-providers/terraform-provider-azurerm#3939 and /terraform-providers/terraform-provider-azurerm#3925. Currently when you use [go-autorest](https://github.com/Azure/go-autorest) and XML error is returned from Azure API, go-autorest fails to decode it, as it has hardcoded treating error messages as JSON:
- https://github.com/Azure/go-autorest/blob/master/autorest/azure/azure.go#L290
- https://github.com/Azure/go-autorest/blob/master/autorest/azure/azure.go#L297

I've tried some dummy fixes borrowed from https://github.com/Azure/azure-sdk-for-go/blob/master/storage/client.go#L977:
```diff
diff --git a/vendor/github.com/Azure/go-autorest/autorest/azure/azure.go b/vendor/github.com/Azure/go-autorest/autorest/azure/azure.go
index 3a0a439f..96f9a5ba 100644
--- a/vendor/github.com/Azure/go-autorest/autorest/azure/azure.go
+++ b/vendor/github.com/Azure/go-autorest/autorest/azure/azure.go
@@ -285,17 +285,24 @@ func WithErrorUnlessStatusCode(codes ...int) autorest.RespondDecorator {
                                var e RequestError
                                defer resp.Body.Close()
 
+                               var encodedAs autorest.EncodedAs
+                               if resp.Header.Get("Content-Type") == "application/xml" {
+                                       encodedAs = autorest.EncodedAsXML
+                               } else {
+                                       encodedAs = autorest.EncodedAsJSON
+                               }
+
                                // Copy and replace the Body in case it does not contain an error object.
                                // This will leave the Body available to the caller.
-                               b, decodeErr := autorest.CopyAndDecode(autorest.EncodedAsJSON, resp.Body, &e)
+                               b, decodeErr := autorest.CopyAndDecode(encodedAs, resp.Body, &e)
```

but apparently more code needs to be changed to get it working.

If this is not a proper place for this issue, feel free to move it to other repository or point me where I should create it.

**Comment by tombuildsstuff** [comment]
Fixed via https://github.com/Azure/go-autorest/pull/465
